"""引擎：模拟、脚本 VM、渲染后端。"""

from __future__ import annotations

from .anm import (
    AnmBank,
    AnmMachine,
    AnmScript,
    InterpChannel,
    SpriteSlot,
    build_bank,
    build_script,
)
from .assembly import (
    GameAssembly,
    GameData,
    ResourcePaths,
    SaveSemantics,
    ScriptSet,
    check_assembly,
)
from .bullets import (
    GRAZE_EXPAND,
    Aim,
    Bullet,
    BulletCollisionSystem,
    BulletCommand,
    BulletDespawned,
    BulletField,
    BulletGraze,
    BulletHit,
    BulletMovementSystem,
    BulletSpawned,
    BulletState,
    BulletTypeSpec,
    Burst,
    CmdFlag,
    DespawnCause,
    rank_lerp,
    rank_lerp_int,
    step_bullet,
)
from .context import Command, CommandQueue, FrameContext
from .core import Pipeline, Slot, System, World, tick_frame
from .events import Event, EventHandler, EventStream
from .input import Button, InputFrame, MenuAction
from .items import (
    ITEM_COLLECT_RADIUS,
    ITEM_COLLECT_SPEED,
    STATE_ATTRACT,
    STATE_FALL,
    STATE_SPAWN,
    Item,
    ItemCollected,
    ItemCollectSystem,
    ItemDropped,
    ItemField,
    ItemMovementSystem,
)
from .lasers import (
    Laser,
    LaserCollisionSystem,
    LaserField,
    LaserGraze,
    LaserHit,
    LaserMovementSystem,
    LaserSpawned,
    LaserState,
    laser_hits_player,
)
from .rng import Rng
from .snapshot import (
    EffectDraw,
    SceneSnapshot,
    SnapshotBuilder,
    SpriteDraw,
    TextDraw,
)

__all__ = [
    "GRAZE_EXPAND",
    "ITEM_COLLECT_RADIUS",
    "ITEM_COLLECT_SPEED",
    "STATE_ATTRACT",
    "STATE_FALL",
    "STATE_SPAWN",
    "Aim",
    "AnmBank",
    "AnmMachine",
    "AnmScript",
    "Bullet",
    "BulletCollisionSystem",
    "BulletCommand",
    "BulletDespawned",
    "BulletField",
    "BulletGraze",
    "BulletHit",
    "BulletMovementSystem",
    "BulletSpawned",
    "BulletState",
    "BulletTypeSpec",
    "Burst",
    "Button",
    "CmdFlag",
    "Command",
    "CommandQueue",
    "DespawnCause",
    "EffectDraw",
    "Event",
    "EventHandler",
    "EventStream",
    "FrameContext",
    "GameAssembly",
    "GameData",
    "InputFrame",
    "InterpChannel",
    "Item",
    "ItemCollectSystem",
    "ItemCollected",
    "ItemDropped",
    "ItemField",
    "ItemMovementSystem",
    "Laser",
    "LaserCollisionSystem",
    "LaserField",
    "LaserGraze",
    "LaserHit",
    "LaserMovementSystem",
    "LaserSpawned",
    "LaserState",
    "MenuAction",
    "Pipeline",
    "ResourcePaths",
    "Rng",
    "SaveSemantics",
    "SceneSnapshot",
    "ScriptSet",
    "Slot",
    "SnapshotBuilder",
    "SpriteDraw",
    "SpriteSlot",
    "System",
    "TextDraw",
    "World",
    "build_bank",
    "build_script",
    "check_assembly",
    "laser_hits_player",
    "rank_lerp",
    "rank_lerp_int",
    "step_bullet",
    "tick_frame",
]
