"""th08 专属 ECL 指令的 handler 绑定: 指令类 → engine 机制 handler。

handler 语义是流派通用件(住 engine/ecl/handlers), 这里只做 v800 专属指令类
到机制 handler 的装配; EclMachine(extra_handlers=...) 注入。
"""

from __future__ import annotations

from ...engine.ecl import Handler
from ...engine.ecl.handlers import control, delegated, mathops, movement
from ...schemas.ecl import (
    Add,
    AddFloat,
    Div,
    DivFloat,
    EclInstr,
    Mod,
    ModFloat,
    Mul,
    MulFloat,
    Sub,
    SubFloat,
)
from .ecl_instrs import (
    AddAssign,
    AddAssignFloat,
    AdvanceClock,
    BeginSpellcardV800,
    CallSubOnBoss,
    ClearBulletsForTransition,
    ClearEnemyFlags,
    DeferBulletPattern,
    DisableDeferBulletPattern,
    Dist,
    DivAssign,
    DivAssignFloat,
    EnableEnemyFlags,
    HideClock,
    ModAssign,
    ModAssignFloat,
    MoveAtPlayerTime,
    MoveBoundaryAware,
    MoveOrbitAroundSelf,
    MoveOrbitV800,
    MovePosTimeV800,
    MoveRandomBiased,
    MulAssign,
    MulAssignFloat,
    RunPendingSub,
    SetBonusUpdatesDisabled,
    SetBossPendingSub,
    SetChildContext,
    SetDeathCallbackSubV800,
    SetDrawGroup,
    SetEnemyFlags,
    SetEnemyManagerValue,
    SetExtraVmFixedOffset,
    SetFormEffect,
    SetGrazeSizeV800,
    SetHitboxSizeV800,
    SetItemDrop,
    SetItemDropCounts,
    SetLastSpellFlags,
    SetMinPlayerDistance,
    SetMoveAnmSeq,
    SetMoveAnmV800,
    SetMovePolar,
    SetNoDamageDuringStop,
    SetOrbitVels,
    SetPhaseStartLife,
    SetPosV800,
    SetShootOffsetV800,
    SetSpecialAnm,
    SetSpecialInteraction,
    SetSpellcardEffectTracking,
    SetStageScriptLabel,
    SetTimerCallback,
    SetVmInterruptV800,
    SpawnAlignmentEffect,
    SpawnFamiliar,
    SpawnFamiliarInherit,
    SpawnFamiliarRel,
    SpawnLaserPatternV800,
    StartStageBackgroundSequence,
    SubAssign,
    SubAssignFloat,
    SuppressTimelineSpawns,
    TestLaserInUse,
    VecFromAngleMag,
)

#: v800 专属指令类 → handler(EclMachine 的 extra_handlers)
ECL_EXTRA_HANDLERS: dict[type[EclInstr], Handler] = {
    # 控制流/VM 机制
    RunPendingSub: control.run_pending_sub,
    SetChildContext: control.set_child_context,
    CallSubOnBoss: control.call_sub_on_boss,
    SetBossPendingSub: control.set_boss_pending_sub,
    # 2 操作数自赋值(复用共享算术的运算语义)
    AddAssign: mathops.int_assign(mathops.INT_BINOP[Add]),
    SubAssign: mathops.int_assign(mathops.INT_BINOP[Sub]),
    MulAssign: mathops.int_assign(mathops.INT_BINOP[Mul]),
    DivAssign: mathops.int_assign(mathops.INT_BINOP[Div]),
    ModAssign: mathops.int_assign(mathops.INT_BINOP[Mod]),
    AddAssignFloat: mathops.float_assign(mathops.FLOAT_BINOP[AddFloat]),
    SubAssignFloat: mathops.float_assign(mathops.FLOAT_BINOP[SubFloat]),
    MulAssignFloat: mathops.float_assign(mathops.FLOAT_BINOP[MulFloat]),
    DivAssignFloat: mathops.float_assign(mathops.FLOAT_BINOP[DivFloat]),
    ModAssignFloat: mathops.float_assign(mathops.FLOAT_BINOP[ModFloat]),
    VecFromAngleMag: mathops.vec_from_angle_mag,
    Dist: mathops.dist,
    # 移动
    SetPosV800: movement.set_pos_v800,
    MovePosTimeV800: movement.move_pos_time_v800,
    MoveAtPlayerTime: movement.move_at_player_time,
    MoveBoundaryAware: movement.move_boundary_aware,
    MoveRandomBiased: movement.move_random_biased,
    SetMovePolar: movement.set_move_polar,
    MoveOrbitV800: movement.move_orbit_v800,
    MoveOrbitAroundSelf: movement.move_orbit_around_self,
    SetOrbitVels: movement.set_orbit_vels,
    SetMinPlayerDistance: movement.set_min_player_distance,
    # 弹幕/激光
    DeferBulletPattern: delegated.bullet_setup,
    DisableDeferBulletPattern: delegated.bullet_setup,
    SetShootOffsetV800: delegated.bullet_setup,
    ClearBulletsForTransition: delegated.clear_bullets,
    SpawnLaserPatternV800: delegated.spawn_laser,
    TestLaserInUse: delegated.laser_control,
    # 使魔/敌人配置
    SpawnFamiliar: delegated.spawn_familiar,
    SpawnFamiliarRel: delegated.spawn_familiar,
    SpawnFamiliarInherit: delegated.spawn_familiar,
    SetMoveAnmSeq: delegated.enemy_config,
    SetMoveAnmV800: delegated.enemy_config,
    SetSpecialAnm: delegated.enemy_config,
    SetHitboxSizeV800: delegated.enemy_config,
    SetGrazeSizeV800: delegated.enemy_config,
    SetSpecialInteraction: delegated.enemy_config,
    SetEnemyFlags: delegated.enemy_config,
    ClearEnemyFlags: delegated.enemy_config,
    EnableEnemyFlags: delegated.enemy_config,
    SetFormEffect: delegated.enemy_config,
    SetTimerCallback: delegated.enemy_config,
    SetDeathCallbackSubV800: delegated.enemy_config,
    SetVmInterruptV800: delegated.enemy_config,
    SetItemDrop: delegated.enemy_config,
    SetItemDropCounts: delegated.enemy_config,
    SetDrawGroup: delegated.enemy_config,
    SetNoDamageDuringStop: delegated.enemy_config,
    SetExtraVmFixedOffset: delegated.enemy_config,
    SetPhaseStartLife: delegated.enemy_config,
    SpawnAlignmentEffect: delegated.enemy_config,
    SetEnemyManagerValue: delegated.enemy_config,
    # boss/符卡/作品机制
    BeginSpellcardV800: delegated.boss_control,
    SetStageScriptLabel: delegated.boss_control,
    SuppressTimelineSpawns: delegated.boss_control,
    SetLastSpellFlags: delegated.boss_control,
    SetSpellcardEffectTracking: delegated.boss_control,
    StartStageBackgroundSequence: delegated.boss_control,
    HideClock: delegated.boss_control,
    AdvanceClock: delegated.boss_control,
    SetBonusUpdatesDisabled: delegated.boss_control,
}
